#!/bin/bash
yum install -y httpd php git

cd /var/www/html



wget https://github.com/fbisel/fred/JamesJamerson_Bass.jpg
mv JamesJamerson_Bass.jpg JamesJamerson_Bass.jpg
wget https://github.com/fbisel/fred/index.php
mv /var/www/html/htaccess /var/www/html/.htaccess

mkdir /var/www/html/Motown
cp /var/www/html/JamesJamerson_Bass.jpg /var/www/html/JamesJamerson_Bass.jpg
cp /var/www/html/index.php /var/www/html/Motown
cp /var/www/html/.htaccess /var/www/html/Motown

sudo systemctl start httpd
sudo systemctl enable httpd
sudo usermod -a -G apache ec2-user
sudo chown -R ec2-user:apache /var/www
sudo chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
find /var/www -type f -exec sudo chmod 0664 {} \;
